// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public static class ButtonManager
{
	public const string ARROW_LEFT = "<";
	public const string ARROW_RIGHT = ">";

	public const string SELECT = "Select";
		public readonly static string NEW_GAME = "New Game";
		public const string CANCEL = "Cancel";
		public readonly static string LOAD_GAME = "Load Game";
		public readonly static string MAIN_MENU = "Main Menu";
		public readonly static string SAVE_GAME = "Save Game";
		public const string YES = "Yes";
		public const string NO = "No";

		public static string[] GetPauseMenuButtons ()
		{
				return new string[] {"Resume", "Save Game", "Load Game", "Exit Game"};
		}

		public static string[] GetMainMenuButtons ()
		{
				return new string[] {		
					"New Game",
			"Load Game",
					"Change Player",
					"Quit Game"
						};
		}
}

